#------------------------------------------------------
# Copyright (c) 2025, Elehobica
# Released under the BSD-2-Clause
# refer to https://opensource.org/licenses/BSD-2-Clause
#------------------------------------------------------

name: Build

on: [push, pull_request]

jobs:
  build-binaries:
    runs-on: ubuntu-latest
    env:
      RELEASE_DIR: Release
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Build
        uses: ./.github/actions/build-and-rename
        with:
          path: .
          build: build
          platform: rp2350
          board: pico2
          identifier: pico2
          output_path: ${{ env.RELEASE_DIR }}
      - name: Upload production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-binaries
          path: |
            ${{ env.RELEASE_DIR }}/*.uf2
            ${{ env.RELEASE_DIR }}/*.elf

  release-tag-condition:
    runs-on: ubuntu-latest
    outputs:
      matched: ${{ steps.check.outputs.matched }}
    steps:
      - name: Check if Release Tag Condition Matched
        id: check
        run: |
          if [[ ${{ github.ref_type }} == 'tag' && ${{ github.ref_name }} =~ ^[0-9]+.[0-9]+.[0-9]+$ ]]; then
            echo "matched=true" >> $GITHUB_OUTPUT
            echo "Release tag condition matched"
          else
            echo "matched=false" >> $GITHUB_OUTPUT
            echo "Release tag condition not matched"
          fi

  call-upload-release-asset:
    needs: [build-binaries, release-tag-condition]
    if: ${{ needs.release-tag-condition.outputs.matched == 'true' }}
    uses: ./.github/workflows/upload-release-asset.yml
    with:
      source_run_id: ${{ github.run_id }}
      artifacts_dirs: "dist-binaries"
